# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

#Build all projects
steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  enabled: false

# Build the projects using Powershell
- powershell: |
    .\psbuild.ps1 -Verbose
  displayName: 'PowerShell Script to execute dotnet build'

#Publish all projects artifacts to Build.ArtifactStagingDirectory
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    projects: '**/*.csproj'
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
    publishWebProjects: false

#Publish all projects artifacts to Azure Pipelines
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: PublishedAartifacts